# Generated by Django 4.0.6 on 2022-08-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Связь Публикация-Категория', 'verbose_name_plural': 'Связи Публикации-Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(help_text='Название категории - 64 символа', max_length=64, unique=True, verbose_name='Название'),
        ),
    ]
