# Generated by Django 4.0.6 on 2022-08-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_categorysubscriber_category_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorysubscriber',
            options={'verbose_name': 'Связь Категория-Подписчик', 'verbose_name_plural': 'Связи Категории-Подписчики'},
        ),
    ]
