# Generated by Django 4.0.6 on 2022-09-27 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_post_is_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='categorysubscriber',
            options={'verbose_name': 'Connection Category-Subscriber', 'verbose_name_plural': 'Connections Categories-Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Connection Publication - Category', 'verbose_name_plural': 'Connections Publications - Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='name_category_en_us',
            field=models.CharField(help_text='Name of category - 64 characters', max_length=64, null=True, unique=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_category_ru',
            field=models.CharField(help_text='Name of category - 64 characters', max_length=64, null=True, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='author',
            name='rating_author',
            field=models.SmallIntegerField(default=0, verbose_name='Рэйтинг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(help_text='Name of category - 64 characters', max_length=64, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, through='news.CategorySubscriber', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers'),
        ),
        migrations.AlterField(
            model_name='categorysubscriber',
            name='throughCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='categorysubscriber',
            name='throughSubscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subscriber'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Publication'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating_comment',
            field=models.SmallIntegerField(default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_comment',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_post',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_created',
            field=models.BooleanField(default=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья')], default='AR', max_length=2, verbose_name='Type of post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating_post',
            field=models.SmallIntegerField(default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_post',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='throughCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='throughPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Publication'),
        ),
    ]
