# Generated by Django 4.0.6 on 2022-09-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_post_en_us',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='header_post_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_post_en_us',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_post_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
